CREATE TABLE dbo.Supplier(
SupplierID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SuppName VARCHAR(20) NOT NULL,
SuppAddress VARCHAR(100) NOT NULL,
SuppDescription VARCHAR(100) NOT NULL,
SuppTelephone VARCHAR(12) NOT NULL,
SuppEmail VARCHAR(50) NOT NULL
);